# Generated by Django 4.0.1 on 2022-01-13 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cattlecount', '0002_alter_cattle_buy_cost_alter_cattle_lot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='lot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cattle', to='cattlecount.lot'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shed_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='cattlecount.shed'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='shed_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot', to='cattlecount.shed'),
        ),
        migrations.AlterField(
            model_name='medrec',
            name='c_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medrec', to='cattlecount.cattle'),
        ),
    ]
